import { adjacency, evidence, groups, notifications, opportunities, people, reading, watches as seedWatches } from './data.js';

const store = (key, fallback) => { try { return JSON.parse(localStorage[key] || 'null') ?? fallback; } catch { return fallback; } };
const state = {
  route: location.hash.replace('#/','') || 'login',
  user: store('bussola_user', null),
  locale: localStorage.bussola_locale || 'PT',
  query: localStorage.bussola_query || 'privacidade em IoT e telemetria em dispositivos restritos',
  watches: store('bussola_watches', seedWatches),
  saved: store('bussola_saved', []),
  read: store('bussola_read', {}),
  feedback: store('bussola_feedback', [])
};
const save = () => { localStorage.bussola_user = JSON.stringify(state.user); localStorage.bussola_locale = state.locale; localStorage.bussola_query = state.query; localStorage.bussola_watches = JSON.stringify(state.watches); localStorage.bussola_saved = JSON.stringify(state.saved); localStorage.bussola_read = JSON.stringify(state.read); localStorage.bussola_feedback = JSON.stringify(state.feedback); };
const $ = (q) => document.querySelector(q);
const toast = (m) => { const el = $('#toast'); el.textContent = m; el.className = 'show'; setTimeout(() => el.className = '', 2400); };
const tag = (x) => `<span class="tag">${x}</span>`;
const page = (k,t,d,a='') => `<div class="title"><div><small>${k}</small><h1>${t}</h1><p>${d}</p></div>${a}</div>`;
const card = (t,b) => `<section class="card"><h2>${t}</h2>${b}</section>`;
const metrics = () => `<div class="metrics">${[['Acompanhamentos ativos','24','+20%'],['Evidencias indexadas','8.736','+715 hoje'],['Adjacencias fortes','18','+5'],['Precisao util','76%','+8 p.p.']].map(m=>`<article class="metric"><small>${m[0]}</small><b>${m[1]}</b><span>${m[2]}</span></article>`).join('')}</div>`;
const nav = [['inicio','Inicio'],['busca','Busca Global'],['descoberta','Descoberta'],['onboarding','Trilha de Entrada'],['torre','Torre de Vigia'],['acompanhamentos','Acompanhamentos'],['oportunidades','Oportunidades'],['grupos','Grupos'],['adjacencia','Mapa de Adjacencia'],['pacotes','Pacotes de Leitura'],['rascunhos','Rascunhos'],['evidencias','Evidencias'],['pessoas','Pessoas Ponte'],['relatorios','Relatorios'],['fontes','Fontes'],['ingestao','Saude da Ingestao'],['chair','Modo Chair'],['notificacoes','Notificacoes'],['perfil','Perfil'],['configuracoes','Configuracoes']];

function go(route){ state.route = route; location.hash = '#/' + route; render(); }
function shell(content){ return `<div class="shell"><aside class="side"><a class="brand" href="#/inicio"><b class="mark">B</b><span><strong>Bussola IETF</strong><small>Conectar. Colaborar. Orientar.</small></span></a><nav>${nav.map(([id,label],i)=>`<a class="${state.route===id?'active':''}" href="#/${id}"><b>${label[0]}</b><span>${label}</span></a>`).join('')}</nav><div class="profile"><b>${state.user?.name || 'Ana Martins'}</b><small>Participante - perfil 85%</small></div></aside><main><header class="top"><input class="search" id="q" value="${state.query}" placeholder="Buscar temas, grupos, documentos..."/><div class="locale">${['PT','ES','EN'].map(l=>`<button data-locale="${l}" class="${state.locale===l?'active':''}">${l}</button>`).join('')}</div><button class="secondary" data-go="notificacoes">${notifications.length}</button><button class="secondary" id="logout">Sair</button></header><section class="content">${content}</section></main></div>`; }
function login(){ return `<main class="login"><section class="login-left"><div class="brand"><b class="mark">B</b><span><strong>Bussola IETF</strong><small>Navegue. Conecte. Contribua.</small></span></div><h1>Navegue o ecossistema de inovacao, pesquisa, tecnologia e futuro.</h1><p>Descubra grupos, acompanhe sinais, gere rascunhos e entenda conexoes entre IRTF e IETF com evidencias rastreaveis.</p></section><form class="auth" id="auth"><h2>Acessar plataforma</h2><p>Use login demo para a apresentacao ou cadastre seu e-mail depois no Supabase.</p><label>E-mail<input id="email" type="email" value="demo@bussola.ietf"></label><label>Senha<input type="password" value="demo12345"></label><button class="primary" style="width:100%">Entrar</button><p class="notice">MVP funcional com dados locais, APIs Vercel e pontos prontos para Supabase.</p></form></main>`; }
function home(){ return page('Visao geral','Encontre seu caminho no IETF','Descubra temas, grupos, documentos e oportunidades para se envolver.') + `<section class="hero"><div><h2>Roteie um tema para grupos, evidencias e proximas acoes.</h2><p>A Bussola organiza Datatracker, RFCs, listas, materiais de reuniao e sinais de adjacencia em recomendacoes auditaveis.</p><div class="route"><input id="route-q" value="${state.query}"><button class="primary" id="route">Rotear tema</button></div></div><div class="compass"></div></section>${metrics()}<div class="layout">${card('Destaques da semana', opportunities.map(opportunity).join(''))}${card('Mapa de adjacencia', graph())}</div>`; }
function busca(){ return page('Busca unificada','Busca Global','Encontre conteudos, grupos, pessoas e evidencias relacionados ao IETF.', '<button class="primary" id="run-search">Buscar</button>') + `<div class="toolbar"><button class="active">Tudo</button><button>Temas</button><button>Grupos</button><button>Documentos</button><button>Evidencias</button></div>${card('Resultados encontrados', results().map(r=>`<div class="row"><b>${r.type}</b><span><strong>${r.title}</strong><br>${r.text}<br>${(r.tags||[]).map(tag).join('')}</span><button class="secondary" data-go="${r.route}">Abrir</button></div>`).join(''))}`; }
function results(){ const rows=[...groups.map(g=>({type:'Grupo',title:g.acronym+' - '+g.name,text:g.description,tags:g.tags,route:'grupos'})),...evidence.map(e=>({type:'Evidencia',title:e.source,text:e.quote,tags:[e.group,e.type],route:'evidencias'})),...people.map(p=>({type:'Pessoa',title:p.name,text:p.org,tags:p.groups,route:'pessoas'})),...opportunities.map(o=>({type:'Oportunidade',title:o.title,text:o.group,tags:[o.priority],route:'oportunidades'}))]; return rows.filter(r=>(r.title+r.text+(r.tags||[]).join()).toLowerCase().includes((state.query.split(' ')[0]||'').toLowerCase())).slice(0,12); }
function descoberta(){ return page('Descoberta explicavel','Descoberta','Roteie perguntas para grupos IRTF/IETF com justificativas e fontes rastreaveis.') + `<div class="panel card"><label>Tema ou pergunta<textarea id="discover">${state.query}</textarea></label><button class="primary" id="analyze">Analisar tema</button></div><div class="layout"><div class="stack">${groups.slice(0,3).map((g,i)=>`<article class="item opportunity"><div><b>${i+1}. ${g.acronym}</b><h3>${g.name}</h3><p>${g.description}</p>${g.tags.map(tag).join('')}</div><b>${[92,86,78][i]}%</b><button class="secondary" data-watch="${g.acronym}">Acompanhar</button></article>`).join('')}</div>${card('Evidencias', evidence.map(evMini).join(''))}</div>`; }
function acompanhamentos(){ return page('Monitoramento','Acompanhamentos','Escolha e gerencie o que a Bussola IETF deve monitorar para voce.','<button class="primary" id="new-watch">Novo acompanhamento</button>') + `<div class="layout"><div class="stack">${state.watches.map(w=>`<article class="watch item"><div><h3>${w.title}</h3><p>${w.type} - ${w.scope}</p>${w.groups.map(tag).join('')}</div><span>${w.cadence}<br>${w.channel}<br>${w.updates} atualizacoes</span><button class="secondary" data-pause="${w.id}">${w.status}</button></article>`).join('')}</div><aside class="panel card"><h2>Criar acompanhamento</h2><label>Tema<input id="watch-title" placeholder="Privacidade em IoT"></label><label>Canal<select id="watch-channel"><option>Painel</option><option>E-mail</option><option>Digest</option></select></label><button class="primary" id="create-watch">Criar acompanhamento</button></aside></div>`; }
function oportunidades(){ return page('Acoes recomendadas','Oportunidades','Itens priorizados por interesses, grupos e atividades recentes.') + `<div class="filters"><button class="active">Todas</button><button>Threads ativas</button><button>Drafts recentes</button><button>Janelas de acao</button></div><div class="layout"><div class="stack">${opportunities.map(opportunity).join('')}</div>${card('Proximos eventos','<p><b>T2TRG Interim</b><br>14:00 UTC</p><p><b>GAIA Working Group Call</b><br>16:00 UTC</p><p><b>IETF 121 - Prague</b><br>19-25 jul 2025</p>')}</div>`; }
function grupos(){ return page('Catalogo canonico','Grupos','Explore grupos de pesquisa, atividade recente, conexoes e documentos chave.') + `<div class="group-grid">${groups.map(g=>`<article class="group card"><div class="badge" style="background:${g.color}">${g.acronym}</div><h3>${g.acronym}</h3><small>${g.name}</small><p>${g.description}</p>${g.tags.map(tag).join('')}<p><b>${g.drafts}</b> drafts - <b>${g.people}</b> participantes - ${g.activity}</p><button class="secondary" data-watch="${g.acronym}">Acompanhar</button> <a class="secondary" href="${g.url}" target="_blank">Fonte oficial</a></article>`).join('')}</div>`; }
function adjacencia(){ return page('Inteligencia relacional','Mapa de Adjacencia','Compare relacoes entre grupos por sinais semanticos, autores, citacoes e mencoes.') + `<div class="layout">${card('Rede atual', graph(true))}${card('Adjacencias detectadas', adjacency.map(a=>`<p><b>${a.a} <-> ${a.b}</b> ${tag(a.score.toFixed(2))}<br>${a.summary}<br>${a.signals.map(tag).join('')}</p>`).join(''))}</div>`; }
function pacotes(){ return page('Entrada guiada','Pacotes de Leitura','Curadoria para entender temas chave e preparar participacao.') + `<div class="layout">${card('Introducao ao T2TRG e adjacencias com CoRE', reading.map((r,i)=>`<div class="row"><b>${i+1}</b><span>${r}</span><button class="secondary" data-read="${i}">${state.read[i]?'Concluido':'Marcar'}</button></div>`).join(''))}${card('Seu progresso', `<b>${Object.values(state.read).filter(Boolean).length} de ${reading.length}</b><p>Itens concluidos neste pacote.</p>`)}</div>`; }
function rascunhos(){ const body='Dear T2TRG,\n\nI am reviewing privacy and telemetry considerations for constrained devices and would appreciate feedback from the group.\n\nQuestions:\n- Are the assumptions aligned with current work?\n- Which drafts or RFCs should be cited?\n- Are there deployment constraints we should consider?\n\nBest regards,'; return page('Mensagens tecnicas','Rascunhos','Prepare mensagens para listas com clareza, evidencias e tom adequado.') + `<div class="layout"><section class="card editor"><label>Grupo<select id="draft-group"><option>T2TRG</option><option>GAIA</option><option>CoRE</option></select></label><label>Assunto<input id="draft-subject" value="Feedback request: privacy telemetry in constrained devices"></label><label>Corpo<textarea id="draft-body">${body}</textarea></label><button class="primary" id="draft">Gerar nova sugestao</button> <button class="secondary" id="copy">Copiar</button></section>${card('Evidencias sugeridas', evidence.map(evMini).join(''))}</div>`; }
function evidencias(){ return page('Auditoria','Evidencias','Cada recomendacao e fundamentada em fontes rastreaveis e verificaveis.') + `<div class="layout">${card('48 evidencias encontradas', evidence.map(e=>`<div class="row"><b>${e.source}</b><span>${e.quote}<br>${tag(e.group)} ${tag(e.type)}</span><b>${e.confidence.toFixed(2)}</b></div>`).join(''))}${card('Evidencia selecionada', `<h3>${evidence[0].source}</h3><p>${evidence[0].quote}</p><button class="secondary" data-feedback="util">Util</button> <button class="secondary" data-feedback="fraca">Fraca</button> <button class="secondary" data-feedback="incorreta">Incorreta</button>`)}</div>`; }
function pessoas(){ return page('Conexoes humanas','Pessoas Ponte','Descubra colaboradores que conectam grupos, temas e documentos.') + card('24 pessoas encontradas', `<table class="table"><thead><tr><th>Pessoa</th><th>Grupos</th><th>Conectados</th><th>Rascunhos</th><th>Forca</th></tr></thead><tbody>${people.map(p=>`<tr><td><b>${p.name}</b><br>${p.org}</td><td>${p.groups.map(tag).join('')}</td><td>${p.connected}</td><td>${p.drafts}</td><td>${p.strength}</td></tr>`).join('')}</tbody></table>`); }
function simples(nome, desc){ return page('Modulo',''+nome,desc) + metrics() + `<div class="grid">${['Resumo','Acoes','Evidencias','Configuracoes'].map(x=>card(x,'<p>Fluxo demonstravel com dados persistidos localmente e APIs Vercel preparadas para Supabase.</p><button class="secondary" data-toast="Acao executada">Executar</button>')).join('')}</div>`; }
function opportunity(o){ return `<article class="opportunity item ${o.tone}"><div><b>${o.priority}</b><h3>${o.title}</h3><p>${o.group} - Evidencias ${o.evidence}</p></div><button class="secondary" data-save="${o.id}">Salvar</button><button class="primary" data-go="rascunhos">${o.action}</button></article>`; }
function evMini(e){ return `<p><b>${e.source}</b><br>${e.quote}<br>${tag(e.group)} ${tag(e.confidence.toFixed(2))}</p>`; }
function graph(big=false){ const ns=[['T2TRG',18,45,'#0ea5a4'],['GAIA',40,18,'#149a49'],['DINRG',72,25,'#8c249b'],['CFRG',42,52,'#143b78'],['CoRE',24,73,'#138a76'],['TLS',58,73,'#0f766e'],['NMRG',74,55,'#2763d3']]; const p=Object.fromEntries(ns.map(n=>[n,[n[1],n[2]]])); const ls=[['T2TRG','GAIA','strong'],['T2TRG','CoRE','strong'],['GAIA','DINRG',''],['CFRG','TLS','strong'],['CoRE','TLS','dash'],['DINRG','NMRG','']]; return `<svg class="graph" viewBox="0 0 100 90">${ls.map(l=>`<line class="${l[2]}" x1="${p[l[0]][0]}" y1="${p[l[0]][1]}" x2="${p[l[1]][0]}" y2="${p[l[1]][1]}"/>`).join('')}${ns.map(n=>`<g><circle cx="${n[1]}" cy="${n[2]}" r="7" stroke="${n[3]}"/><text x="${n[1]}" y="${n[2]+1}">${n[0]}</text></g>`).join('')}</svg>`; }

function bind(){ $('#auth')?.addEventListener('submit',e=>{e.preventDefault(); state.user={name:($('#email')?.value||'demo').split('@')[0], role:'Participante'}; save(); go('inicio');}); $('#logout')?.addEventListener('click',()=>{state.user=null;save();go('login')}); $('#q')?.addEventListener('keydown',e=>{if(e.key==='Enter'){state.query=e.target.value;save();go('busca')}}); $('#route')?.addEventListener('click',()=>{state.query=$('#route-q').value;save();go('descoberta')}); $('#analyze')?.addEventListener('click',()=>{state.query=$('#discover').value;save();toast('Tema analisado')}); $('#create-watch')?.addEventListener('click',()=>{state.watches.unshift({id:'w'+Date.now(),title:$('#watch-title').value||'Novo acompanhamento',type:'Tema',scope:'IRTF + IETF',groups:['T2TRG','CoRE'],cadence:'Semanal',channel:$('#watch-channel').value,updates:0,status:'Ativo'});save();render();}); $('#draft')?.addEventListener('click',async()=>{const group=$('#draft-group').value; const subject=$('#draft-subject').value; try{const r=await fetch('/api/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({group,subject,query:state.query})}); $('#draft-body').value=(await r.json()).body;}catch{$('#draft-body').value+='\n\nSuggested evidence: T2TRG charter and CoRE draft.'} toast('Rascunho gerado');}); $('#copy')?.addEventListener('click',()=>navigator.clipboard?.writeText($('#draft-body').value).then(()=>toast('Texto copiado'))); document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); document.querySelectorAll('[data-locale]').forEach(b=>b.onclick=()=>{state.locale=b.dataset.locale;save();render()}); document.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{state.watches.unshift({id:'w'+Date.now(),title:'Acompanhar '+b.dataset.watch,type:'Grupo',scope:'IRTF + IETF',groups:[b.dataset.watch],cadence:'Semanal',channel:'Painel',updates:0,status:'Ativo'});save();toast('Acompanhamento criado')}); document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{if(!state.saved.includes(b.dataset.save))state.saved.push(b.dataset.save);save();toast('Oportunidade salva')}); document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{state.read[b.dataset.read]=!state.read[b.dataset.read];save();render()}); document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{state.feedback.push({rating:b.dataset.feedback,at:new Date().toISOString()});save();toast('Feedback registrado')}); document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast)); }
function render(){ if(!state.user && state.route!=='login') state.route='login'; const routes={inicio:home,busca,descoberta,onboarding:()=>simples('Trilha de Entrada','Configure idioma, experiencia, grupos e canais.'),torre:()=>simples('Torre de Vigia','Sinais, FYI, maturacao e janelas de acao.'),acompanhamentos,oportunidades,grupos,adjacencia,pacotes,rascunhos,evidencias,pessoas,relatorios:()=>simples('Relatorios','Gere relatorios e exportacoes de pesquisa.'),fontes:()=>simples('Fontes de Dados','Monitore Datatracker, RFC Editor, Mailarchive e materiais.'),ingestao:()=>simples('Saude da Ingestao','Acompanhe pipeline, latencia, erros e embeddings.'),chair:()=>simples('Modo Chair','Visao estrategica para coordenacao de grupos.'),notificacoes:()=>simples('Notificacoes','Central de alertas, FYI e janelas de acao.'),perfil:()=>simples('Perfil do Usuario','Preferencias, grupos, contribuicoes e progresso.'),configuracoes:()=>simples('Configuracoes','Idioma, notificacoes, fontes e privacidade.')}; $('#app').innerHTML=state.route==='login'?login():shell((routes[state.route]||home)()); bind(); }
addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'inicio';render()});
render();
