import { adjacency as seedAdjacency, evidence as seedEvidence, groups as seedGroups, notifications, opportunities, people, reading, watches as seedWatches } from './data.js';
import { fetchCatalog } from './supabase.js';

// Catalogo mutavel: inicia com dados-semente e e substituido pelos dados reais
// do Supabase assim que carregam (com fallback ao proprio seed em caso de falha).
let groups = seedGroups, evidence = seedEvidence, adjacency = seedAdjacency;

const store = (key, fallback) => { try { return JSON.parse(localStorage[key] || 'null') ?? fallback; } catch { return fallback; } };
const state = {
  route: location.hash.replace('#/','') || 'login',
  user: store('bussola_user', null),
  locale: localStorage.bussola_locale || 'PT',
  query: localStorage.bussola_query || 'privacidade em IoT e telemetria em dispositivos restritos',
  watches: store('bussola_watches', seedWatches),
  saved: store('bussola_saved', []),
  read: store('bussola_read', {}),
  feedback: store('bussola_feedback', []),
  graphPositions: store('bussola_graph_positions', null),
  selectedGraphNode: store('bussola_selected_graph_node', 'T2TRG'),
  disc: { q: null, candidates: null, loading: false, engine: null },
  srch: { q: null, rows: null, loading: false, engine: null }
};
const save = () => { localStorage.bussola_user = JSON.stringify(state.user); localStorage.bussola_locale = state.locale; localStorage.bussola_query = state.query; localStorage.bussola_watches = JSON.stringify(state.watches); localStorage.bussola_saved = JSON.stringify(state.saved); localStorage.bussola_read = JSON.stringify(state.read); localStorage.bussola_feedback = JSON.stringify(state.feedback); localStorage.bussola_graph_positions = JSON.stringify(state.graphPositions); localStorage.bussola_selected_graph_node = JSON.stringify(state.selectedGraphNode); };
const $ = (q) => document.querySelector(q);
const toast = (m) => { const el = $('#toast'); el.textContent = m; el.className = 'show'; setTimeout(() => el.className = '', 2400); };
const tag = (x) => `<span class="tag">${x}</span>`;
const page = (k,t,d,a='') => `<div class="title"><div><small>${k}</small><h1>${t}</h1><p>${d}</p></div>${a}</div>`;
const card = (t,b) => `<section class="card"><h2>${t}</h2>${b}</section>`;
const metrics = () => { const m=[['Grupos no catalogo', String(groups.length)],['Evidencias', String(evidence.length)],['Adjacencias', String(adjacency.length)],['Acompanhamentos', String(state.watches.length)]]; return `<div class="metrics">${m.map(x=>`<article class="metric"><small>${x[0]}</small><b>${x[1]}</b></article>`).join('')}</div>`; };
const nav = [['inicio','Inicio'],['descoberta','Descoberta'],['busca','Busca Global'],['grupos','Grupos'],['adjacencia','Mapa de Adjacencia'],['evidencias','Evidencias'],['pacotes','Pacotes de Leitura'],['rascunhos','Rascunhos'],['acompanhamentos','Acompanhamentos'],['oportunidades','Oportunidades'],['pessoas','Pessoas Ponte']];

function go(route){ state.route = route; location.hash = '#/' + route; render(); }
function shell(content){ return `<div class="shell"><aside class="side"><a class="brand" href="#/inicio"><b class="mark">B</b><span><strong>Bussola IETF</strong><small>Conectar. Colaborar. Orientar.</small></span></a><nav>${nav.map(([id,label])=>`<a class="${state.route===id?'active':''}" href="#/${id}"><span>${label}</span></a>`).join('')}</nav><div class="profile"><b>${state.user?.name || 'Ana Martins'}</b><small>Participante - perfil 85%</small></div></aside><main><header class="top"><input class="search" id="q" value="${state.query}" placeholder="Buscar temas, grupos, documentos..."/><div class="locale">${['PT','ES','EN'].map(l=>`<button data-locale="${l}" class="${state.locale===l?'active':''}">${l}</button>`).join('')}</div><button class="secondary" id="logout">Sair</button></header><section class="content">${content}</section></main></div>`; }
function login(){ return `<main class="login"><section class="login-left"><div class="brand"><b class="mark">B</b><span><strong>Bussola IETF</strong><small>Navegue. Conecte. Contribua.</small></span></div><h1>Navegue o ecossistema de inovacao, pesquisa, tecnologia e futuro.</h1><p>Descubra grupos, acompanhe sinais, gere rascunhos e entenda conexoes entre IRTF e IETF com evidencias rastreaveis.</p></section><form class="auth" id="auth"><h2>Acessar plataforma</h2><p>Login demo para a apresentacao. Use qualquer e-mail para entrar.</p><label>E-mail<input id="email" type="email" value="demo@bussola.ietf"></label><label>Senha<input id="password" type="password" value="demo12345"></label><button class="primary" style="width:100%" type="submit">Entrar</button><p class="notice">MVP com login ficticio. Catalogo (grupos, evidencias, adjacencias) carregado do Supabase com fallback local.</p></form></main>`; }
function home(){ return page('Visao geral','Encontre seu caminho no IETF','Descubra temas, grupos, documentos e oportunidades para se envolver.') + `<section class="hero"><div><h2>Roteie um tema para grupos, evidencias e proximas acoes.</h2><p>A Bussola organiza Datatracker, RFCs, listas, materiais de reuniao e sinais de adjacencia em recomendacoes auditaveis.</p><div class="route"><input id="route-q" value="${state.query}"><button class="primary" id="route">Rotear tema</button></div></div><div class="compass"></div></section>${metrics()}<div class="layout">${card('Destaques da semana', opportunities.map(opportunity).join(''))}${card('Mapa de adjacencia', graph())}</div>`; }
function busca(){ if(state.srch.q!==state.query && !state.srch.loading) runSearch(); const fresh=state.srch.q===state.query && state.srch.rows; const rs=fresh?state.srch.rows:resultsClient(); const engine=fresh?state.srch.engine:'cliente (lexical)'; return page('Busca unificada','Busca Global','Encontre conteudos, grupos, pessoas e evidencias relacionados ao IETF.', '<button class="primary" id="run-search">Buscar</button>') + `<div class="toolbar"><button class="active">Tudo</button><button>Temas</button><button>Grupos</button><button>Documentos</button><button>Evidencias</button></div>${card(`${rs.length} resultado(s) para "${state.query}" - motor: ${engine}`, rs.length?rs.map(r=>`<div class="row"><b>${r.type}</b><span><strong>${r.title}</strong><br>${r.text||''}<br>${(r.tags||[]).map(tag).join('')}</span><button class="secondary" data-go="${r.route}">Abrir</button></div>`).join(''):'<p class="notice">Nenhum resultado. Tente outros termos.</p>')}`; }
// Busca global real (SDD RF2): monta linhas de grupos, evidencias, pessoas e
// oportunidades e as pontua contra todos os termos da consulta (match em tag
// pesa mais). Ranqueia por relevancia; consulta vazia lista tudo.
function searchRows(){ return [...groups.map(g=>({type:'Grupo',title:g.acronym+' - '+g.name,text:g.description,tags:g.tags,route:'grupos'})),...evidence.map(e=>({type:'Evidencia',title:e.source,text:e.quote,tags:[e.group,e.type],route:'evidencias'})),...people.map(p=>({type:'Pessoa',title:p.name,text:p.org,tags:p.groups,route:'pessoas'})),...opportunities.map(o=>({type:'Oportunidade',title:o.title,text:o.group,tags:[o.priority],route:'oportunidades'}))]; }
function resultsClient(){ const ts=terms(state.query); const rows=searchRows(); if(!ts.length) return rows.slice(0,12); const norm=(x)=>(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); const scored=rows.map(r=>{ const tgs=(r.tags||[]).map(norm); const hay=norm(r.title+' '+r.text+' '+(r.tags||[]).join(' ')); let s=0; for(const t of ts){ if(tgs.some(x=>x.includes(t)))s+=2; else if(hay.includes(t))s+=1; } return { r, s }; }); return scored.filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,12).map(x=>x.r); }
// Busca via API (motor Postgres full-text) com fallback ao scorer do cliente.
async function runSearch(){ const q=state.query; if(state.srch.loading) return; state.srch.loading=true; let rows, engine; try{ const r=await fetch('/api/search?q='+encodeURIComponent(q)); const j=await r.json(); if(j&&j.engine==='postgres-fts'&&Array.isArray(j.results)){ rows=j.results; engine='Postgres full-text'; } else throw new Error('unavailable'); }catch{ rows=resultsClient(); engine='cliente (lexical)'; } state.srch={ q, rows, engine, loading:false }; if(state.route==='busca') render(); }
// Roteamento explicavel (SDD RF3/UC1): pontua cada grupo real do catalogo
// contra os termos da consulta. Correspondencia em tag pesa mais que no nome,
// que pesa mais que na descricao. Sem correspondencia -> score 0 (sem % falso).
function terms(q){ return (q||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9]+/).filter(t=>t.length>2); }
function scoreGroup(g, ts){ const name=(g.acronym+' '+g.name).toLowerCase(); const desc=(g.description||'').toLowerCase(); const tgs=(g.tags||[]).join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); let s=0; const matched=[]; for(const t of ts){ let hit=0; if(tgs.includes(t))hit=3; else if(name.includes(t))hit=2; else if(desc.includes(t))hit=1; if(hit){ s+=hit; matched.push(t); } } return { s, matched }; }
function discoverCandidates(q){ const ts=terms(q); const scored=groups.map(g=>({ g, ...scoreGroup(g,ts) })); const hits=scored.filter(x=>x.s>0).sort((a,b)=>b.s-a.s); const list=(hits.length?hits:scored).slice(0,4); const max=Math.max(1,...list.map(x=>x.s)); return list.map(x=>({ ...x, pct: x.s>0?Math.round(55+40*(x.s/max)):0 })); }
// Candidatos no formato unificado a partir do scorer do cliente (fallback).
function currentDiscoverClient(q){ return discoverCandidates(q).map(c=>({ acronym:c.g.acronym, name:c.g.name, ecosystem:c.g.kind, score:c.pct, snippet:c.g.description, url:c.g.url, matched:c.matched, evidence: evidence.filter(e=>e.group===c.g.acronym).map(e=>({snippet:e.quote,url:e.url})) })); }
// Descoberta via API (motor Postgres full-text) com fallback ao scorer do cliente.
async function runDiscover(){ const q=state.query; if(state.disc.loading) return; state.disc.loading=true; let candidates, engine; try{ const r=await fetch('/api/discover?q='+encodeURIComponent(q)); const j=await r.json(); if(j&&j.engine==='postgres-fts'&&Array.isArray(j.candidates)){ candidates=j.candidates; engine='Postgres full-text'; } else throw new Error('unavailable'); }catch{ candidates=currentDiscoverClient(q); engine='cliente (lexical)'; } state.disc={ q, candidates, engine, loading:false }; if(state.route==='descoberta') render(); }
function descoberta(){ if(state.disc.q!==state.query && !state.disc.loading) runDiscover(); const fresh=state.disc.q===state.query && state.disc.candidates; const cands=fresh?state.disc.candidates:currentDiscoverClient(state.query); const engine=fresh?state.disc.engine:'cliente (lexical)'; return page('Descoberta explicavel','Descoberta','Roteie perguntas para grupos IRTF/IETF com justificativas e fontes rastreaveis.') + `<div class="panel card"><label>Tema ou pergunta<textarea id="discover">${state.query}</textarea></label><button class="primary" id="analyze">Analisar tema</button><p class="notice">Motor: ${engine}</p></div><div class="layout"><div class="stack">${cands.length?cands.map((c,i)=>{ const just=c.matched?(c.matched.length?`Correspondencia: ${c.matched.map(tag).join('')}`:'Sem correspondencia direta com os termos.'):(c.snippet?'':''); const ecos=c.ecosystem?tag(c.ecosystem):''; return `<article class="item opportunity"><div><b>${i+1}. ${c.acronym}</b><h3>${c.name}</h3><p>${c.snippet||''}</p>${ecos}<p class="notice">${just}${c.evidence&&c.evidence.length?` ${just?'- ':''}${c.evidence.length} evidencia(s)`:''}</p></div><b>${c.score?c.score+'%':'--'}</b><button class="secondary" data-watch="${c.acronym}">Acompanhar</button></article>`; }).join(''):'<p>Nenhum grupo correspondente.</p>'}</div>${card('Evidencias', evidence.map(evMini).join(''))}</div>`; }
function acompanhamentos(){ return page('Monitoramento','Acompanhamentos','Escolha e gerencie o que a Bussola IETF deve monitorar para voce.','<button class="primary" id="new-watch">Novo acompanhamento</button>') + `<div class="layout"><div class="stack">${state.watches.map(w=>`<article class="watch item"><div><h3>${w.title}</h3><p>${w.type} - ${w.scope}</p>${w.groups.map(tag).join('')}</div><span>${w.cadence}<br>${w.channel}<br>${w.updates} atualizacoes</span><button class="secondary" data-pause="${w.id}">${w.status}</button></article>`).join('')}</div><aside class="panel card"><h2>Criar acompanhamento</h2><label>Tema<input id="watch-title" placeholder="Privacidade em IoT"></label><label>Canal<select id="watch-channel"><option>Painel</option><option>E-mail</option><option>Digest</option></select></label><button class="primary" id="create-watch">Criar acompanhamento</button></aside></div>`; }
function oportunidades(){ return page('Acoes recomendadas','Oportunidades','Itens priorizados por interesses, grupos e atividades recentes.') + `<div class="filters"><button class="active">Todas</button><button>Threads ativas</button><button>Drafts recentes</button><button>Janelas de acao</button></div><div class="layout"><div class="stack">${opportunities.map(opportunity).join('')}</div>${card('Proximos eventos','<p><b>T2TRG Interim</b><br>14:00 UTC</p><p><b>GAIA Working Group Call</b><br>16:00 UTC</p><p><b>IETF 121 - Prague</b><br>19-25 jul 2025</p>')}</div>`; }
function grupos(){ return page('Catalogo canonico','Grupos','Explore grupos de pesquisa, atividade recente, conexoes e documentos chave.') + `<div class="group-grid">${groups.map(g=>`<article class="group card"><div class="badge" style="background:${g.color}">${g.acronym}</div><h3>${g.acronym}</h3><small>${g.name}</small><p>${g.description}</p>${(g.tags||[]).map(tag).join('')}<p>${g.drafts!=null?`<b>${g.drafts}</b> drafts - <b>${g.people}</b> participantes - ${g.activity}`:`${g.kind} - <span class="tag">${g.status||'ativo'}</span>`}</p><button class="secondary" data-watch="${g.acronym}">Acompanhar</button> <a class="secondary" href="${g.url}" target="_blank">Fonte oficial</a></article>`).join('')}</div>`; }
function adjacencia(){ return page('Inteligencia relacional','Mapa de Adjacencia','Compare relacoes entre grupos por sinais semanticos, autores, citacoes e mencoes.') + `<div class="layout map-layout">${card('Rede atual', graph(true) + '<p class="map-help">Arraste os grupos para reorganizar. Clique em um grupo ou conexao para ver o resumo.</p>')}<div class="stack">${card('Resumo selecionado', graphSummary())}${card('Adjacencias detectadas', adjacency.map(a=>`<button class="adj-row" data-select-edge="${a.a}|${a.b}"><b>${a.a} <-> ${a.b}</b> ${tag(a.score.toFixed(2))}<br><span>${a.summary}</span><br>${a.signals.map(tag).join('')}</button>`).join(''))}</div></div>`; }
function pacotes(){ return page('Entrada guiada','Pacotes de Leitura','Curadoria para entender temas chave e preparar participacao.') + `<div class="layout">${card('Introducao ao T2TRG e adjacencias com CoRE', reading.map((r,i)=>`<div class="row"><b>${i+1}</b><span>${r}</span><button class="secondary" data-read="${i}">${state.read[i]?'Concluido':'Marcar'}</button></div>`).join(''))}${card('Seu progresso', `<b>${Object.values(state.read).filter(Boolean).length} de ${reading.length}</b><p>Itens concluidos neste pacote.</p>`)}</div>`; }
function rascunhos(){ const body='Dear T2TRG,\n\nI am reviewing privacy and telemetry considerations for constrained devices and would appreciate feedback from the group.\n\nQuestions:\n- Are the assumptions aligned with current work?\n- Which drafts or RFCs should be cited?\n- Are there deployment constraints we should consider?\n\nBest regards,'; return page('Mensagens tecnicas','Rascunhos','Prepare mensagens para listas com clareza, evidencias e tom adequado.') + `<div class="layout"><section class="card editor"><label>Grupo<select id="draft-group"><option>T2TRG</option><option>GAIA</option><option>CoRE</option></select></label><label>Assunto<input id="draft-subject" value="Feedback request: privacy telemetry in constrained devices"></label><label>Corpo<textarea id="draft-body">${body}</textarea></label><button class="primary" id="draft">Gerar nova sugestao</button> <button class="secondary" id="copy">Copiar</button></section>${card('Evidencias sugeridas', evidence.map(evMini).join(''))}</div>`; }
function evidencias(){ return page('Auditoria','Evidencias','Cada recomendacao e fundamentada em fontes rastreaveis e verificaveis.') + `<div class="layout">${card('48 evidencias encontradas', evidence.map(e=>`<div class="row"><b>${e.source}</b><span>${e.quote}<br>${tag(e.group)} ${tag(e.type)}</span><b>${e.confidence.toFixed(2)}</b></div>`).join(''))}${card('Evidencia selecionada', `<h3>${evidence[0].source}</h3><p>${evidence[0].quote}</p><button class="secondary" data-feedback="util">Util</button> <button class="secondary" data-feedback="fraca">Fraca</button> <button class="secondary" data-feedback="incorreta">Incorreta</button>`)}</div>`; }
function pessoas(){ return page('Conexoes humanas','Pessoas Ponte','Descubra colaboradores que conectam grupos, temas e documentos.') + card('24 pessoas encontradas', `<table class="table"><thead><tr><th>Pessoa</th><th>Grupos</th><th>Conectados</th><th>Rascunhos</th><th>Forca</th></tr></thead><tbody>${people.map(p=>`<tr><td><b>${p.name}</b><br>${p.org}</td><td>${p.groups.map(tag).join('')}</td><td>${p.connected}</td><td>${p.drafts}</td><td>${p.strength}</td></tr>`).join('')}</tbody></table>`); }
function opportunity(o){ return `<article class="opportunity item ${o.tone}"><div><b>${o.priority}</b><h3>${o.title}</h3><p>${o.group} - Evidencias ${o.evidence}</p></div><button class="secondary" data-save="${o.id}">Salvar</button><button class="primary" data-go="rascunhos">${o.action}</button></article>`; }
function evMini(e){ return `<p><b>${e.source}</b><br>${e.quote}<br>${tag(e.group)} ${tag(e.confidence.toFixed(2))}</p>`; }
const graphNodes = [
  {id:'T2TRG',name:'Thing-to-Thing',kind:'IRTF',color:'#0ea5a4',x:20,y:34,summary:'Telemetria, descoberta, privacidade e comunicacao entre coisas em ambientes restritos.'},
  {id:'GAIA',name:'Global Access',kind:'IRTF',color:'#149a49',x:39,y:15,summary:'Inclusao digital, acesso universal e infraestrutura comunitaria.'},
  {id:'DINRG',name:'Decentralized Internet',kind:'IRTF',color:'#8c249b',x:70,y:18,summary:'Governanca, identidade e arquiteturas descentralizadas para a Internet.'},
  {id:'CFRG',name:'Crypto Forum',kind:'IRTF',color:'#143b78',x:42,y:39,summary:'Base criptografica aplicada para seguranca, privacidade e transporte.'},
  {id:'CoRE',name:'Constrained REST',kind:'IETF',color:'#138a76',x:26,y:60,summary:'Ponte IETF para REST, CoAP, seguranca e dispositivos restritos.'},
  {id:'TLS',name:'Transport Security',kind:'IETF',color:'#0f766e',x:56,y:61,summary:'Seguranca de transporte e criptografia aplicada em padroes implantados.'},
  {id:'NMRG',name:'Network Management',kind:'IRTF',color:'#2763d3',x:75,y:43,summary:'Operacao, medicao, automacao e gestao de redes.'}
];
const graphEdges = [
  {a:'T2TRG',b:'GAIA',cls:'semantic',score:.74,label:'Inclusao e IoT'},
  {a:'T2TRG',b:'CoRE',cls:'strong',score:.86,label:'Semantico + citacao'},
  {a:'GAIA',b:'DINRG',cls:'semantic',score:.78,label:'Governanca'},
  {a:'DINRG',b:'NMRG',cls:'explicit',score:.62,label:'Mencoes'},
  {a:'CFRG',b:'TLS',cls:'strong',score:.82,label:'Criptografia'},
  {a:'CFRG',b:'T2TRG',cls:'citation',score:.58,label:'Seguranca'},
  {a:'CoRE',b:'TLS',cls:'rare',score:.65,label:'Termos raros'},
  {a:'GAIA',b:'TLS',cls:'citation',score:.42,label:'Baixa intensidade'},
  {a:'CFRG',b:'DINRG',cls:'semantic',score:.55,label:'Identidade'}
];
function graphPositions(){ const defaults=Object.fromEntries(graphNodes.map(n=>[n.id,{x:n.x,y:n.y}])); return {...defaults,...(state.graphPositions||{})}; }
function graph(big=false){ const pos=graphPositions(); const selected=state.selectedGraphNode||'T2TRG'; return `<div class="adjacency-map-wrap"><svg class="graph ${big?'large':''}" data-graph-map="${big?'large':'mini'}" viewBox="0 0 100 76" role="img" aria-label="Mapa de adjacencia interativo"><rect class="map-bg" x="2" y="2" width="96" height="72" rx="4"/>${graphEdges.map(e=>{const a=pos[e.a],b=pos[e.b],active=selected===e.a||selected===e.b||selected===`${e.a}|${e.b}`||selected===`${e.b}|${e.a}`;return `<g class="graph-edge ${e.cls} ${active?'active':''}" data-edge="${e.a}|${e.b}" data-source="${e.a}" data-target="${e.b}"><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-1.4}">${e.score.toFixed(2)}</text></g>`}).join('')}${graphNodes.map(n=>{const p=pos[n.id],active=selected===n.id;return `<g class="graph-node ${active?'active':''}" data-node="${n.id}" transform="translate(${p.x} ${p.y})" style="--node:${n.color}"><circle r="${big?4.9:4.2}"/><text class="node-initials" y="1.2">${n.id.slice(0,2)}</text><rect class="node-label-bg" x="-8.8" y="6.6" width="17.6" height="5.5" rx="2.4"/><text class="node-label" y="10.5">${n.id}</text></g>`}).join('')}</svg></div>`; }
function graphSummary(){ const selected=state.selectedGraphNode||'T2TRG'; const edge=selected.includes('|')?graphEdges.find(e=>`${e.a}|${e.b}`===selected||`${e.b}|${e.a}`===selected):null; if(edge){const rel=adjacency.find(a=>(a.a===edge.a&&a.b===edge.b)||(a.a===edge.b&&a.b===edge.a)); return `<div class="map-summary"><small>Conexao</small><h3>${edge.a} <-> ${edge.b}</h3><p>${rel?.summary||edge.label}</p><div class="summary-metrics"><span><b>${edge.score.toFixed(2)}</b> confianca</span><span>${edge.label}</span></div>${(rel?.signals||[edge.cls]).map(tag).join('')}</div>`;} const node=graphNodes.find(n=>n.id===selected)||graphNodes[0]; const group=groups.find(g=>g.acronym===node.id); const edges=graphEdges.filter(e=>e.a===node.id||e.b===node.id).sort((a,b)=>b.score-a.score); return `<div class="map-summary"><small>${node.kind}</small><h3>${node.id} · ${group?.name||node.name}</h3><p>${group?.description||node.summary}</p><div class="summary-metrics"><span><b>${edges.length}</b> conexoes</span><span><b>${group?.drafts??'--'}</b> drafts</span><span><b>${group?.people??'--'}</b> pessoas</span></div><h4>Conexoes fortes</h4>${edges.slice(0,3).map(e=>`<button class="summary-link" data-select-edge="${e.a}|${e.b}">${e.a===node.id?e.b:e.a}<span>${e.score.toFixed(2)}</span></button>`).join('')}</div>`; }
function graphPoint(svg,event){ const p=svg.createSVGPoint(); p.x=event.clientX; p.y=event.clientY; return p.matrixTransform(svg.getScreenCTM().inverse()); }
function updateGraph(svg){ const pos=graphPositions(); svg.querySelectorAll('[data-edge]').forEach(edge=>{const l=edge.querySelector('line'),t=edge.querySelector('text'),a=pos[edge.dataset.source],b=pos[edge.dataset.target]; if(!a||!b)return; l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y);t.setAttribute('x',(a.x+b.x)/2);t.setAttribute('y',(a.y+b.y)/2-1.4);}); }
function bindGraph(){ document.querySelectorAll('[data-select-edge]').forEach(b=>b.onclick=()=>{state.selectedGraphNode=b.dataset.selectEdge;save();render();}); document.querySelectorAll('[data-graph-map]').forEach(svg=>{let drag=null; svg.querySelectorAll('[data-edge]').forEach(e=>e.addEventListener('click',ev=>{ev.stopPropagation();state.selectedGraphNode=e.dataset.edge;save();render();})); svg.querySelectorAll('[data-node]').forEach(n=>{n.addEventListener('click',ev=>{ev.stopPropagation();state.selectedGraphNode=n.dataset.node;save();render();}); n.addEventListener('pointerdown',ev=>{if(svg.dataset.graphMap!=='large')return; ev.preventDefault(); const cur=graphPositions()[n.dataset.node],p=graphPoint(svg,ev); drag={node:n,id:n.dataset.node,dx:p.x-cur.x,dy:p.y-cur.y}; n.classList.add('dragging'); n.setPointerCapture(ev.pointerId);}); n.addEventListener('pointermove',ev=>{if(!drag||drag.node!==n)return; const p=graphPoint(svg,ev); state.graphPositions={...graphPositions()}; state.graphPositions[drag.id]={x:Math.max(8,Math.min(92,p.x-drag.dx)),y:Math.max(10,Math.min(66,p.y-drag.dy))}; const q=state.graphPositions[drag.id]; n.setAttribute('transform',`translate(${q.x} ${q.y})`); updateGraph(svg);}); n.addEventListener('pointerup',ev=>{if(!drag||drag.node!==n)return; n.releasePointerCapture(ev.pointerId); n.classList.remove('dragging'); state.selectedGraphNode=drag.id; drag=null; save(); render();});});}); }

function bind(){ $('#auth')?.addEventListener('submit',e=>{e.preventDefault(); state.user={name:($('#email')?.value||'demo').split('@')[0], role:'Participante'}; save(); go('inicio');}); $('#logout')?.addEventListener('click',()=>{state.user=null;save();go('login')}); $('#q')?.addEventListener('keydown',e=>{if(e.key==='Enter'){state.query=e.target.value;save();go('busca')}}); $('#route')?.addEventListener('click',()=>{state.query=$('#route-q').value;save();go('descoberta')}); $('#run-search')?.addEventListener('click',()=>{state.query=$('#q')?.value||state.query;save();render()}); $('#analyze')?.addEventListener('click',()=>{state.query=$('#discover').value;save();render();toast('Tema analisado')}); $('#create-watch')?.addEventListener('click',()=>{state.watches.unshift({id:'w'+Date.now(),title:$('#watch-title').value||'Novo acompanhamento',type:'Tema',scope:'IRTF + IETF',groups:['T2TRG','CoRE'],cadence:'Semanal',channel:$('#watch-channel').value,updates:0,status:'Ativo'});save();render();}); $('#draft')?.addEventListener('click',async()=>{const group=$('#draft-group').value; const subject=$('#draft-subject').value; try{const r=await fetch('/api/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({group,subject,query:state.query})}); $('#draft-body').value=(await r.json()).body;}catch{$('#draft-body').value+='\n\nSuggested evidence: T2TRG charter and CoRE draft.'} toast('Rascunho gerado');}); $('#copy')?.addEventListener('click',()=>navigator.clipboard?.writeText($('#draft-body').value).then(()=>toast('Texto copiado'))); document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); document.querySelectorAll('[data-locale]').forEach(b=>b.onclick=()=>{state.locale=b.dataset.locale;save();render()}); document.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{state.watches.unshift({id:'w'+Date.now(),title:'Acompanhar '+b.dataset.watch,type:'Grupo',scope:'IRTF + IETF',groups:[b.dataset.watch],cadence:'Semanal',channel:'Painel',updates:0,status:'Ativo'});save();toast('Acompanhamento criado')}); document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{if(!state.saved.includes(b.dataset.save))state.saved.push(b.dataset.save);save();toast('Oportunidade salva')}); document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{state.read[b.dataset.read]=!state.read[b.dataset.read];save();render()}); document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{state.feedback.push({rating:b.dataset.feedback,at:new Date().toISOString()});save();toast('Feedback registrado')}); document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast)); bindGraph(); }
function render(){ if(!state.user && state.route!=='login') state.route='login'; const routes={inicio:home,descoberta,busca,grupos,adjacencia,evidencias,pacotes,rascunhos,acompanhamentos,oportunidades,pessoas}; $('#app').innerHTML=state.route==='login'?login():shell((routes[state.route]||home)()); bind(); }
addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'inicio';render()});

// Carrega o catalogo real (grupos, evidencias, adjacencias) do Supabase e
// re-renderiza. Login e ficticio; os dados do catalogo sao reais (com fallback).
async function loadCatalog(){ const c=await fetchCatalog(); groups=c.groups; evidence=c.evidence; adjacency=c.adjacency; render(); }

render();
loadCatalog();
